
# coding: utf-8
# AUTOGENERATED BY appgen on 2024-12-02
# Copyright (C) Nyimbi Odero, 2024
# MIT License


import os
import sys
import enum
import inspect
import datetime
import shutil
from datetime import timedelta, datetime, date

from sqlalchemy.orm import relationship, query, defer, deferred, column_property, mapper
from sqlalchemy.schema import FetchedValue
from sqlalchemy.ext.hybrid import hybrid_property, hybrid_method
from sqlalchemy import (
    create_engine, inspect, MetaData, Table, Column,  ForeignKey, Identity, Index,
    Sequence, Float, Text, BigInteger, Date, Integer, String, SmallInteger,
    DateTime, Time, Boolean,  Interval, Numeric, LargeBinary,Enum,
    CheckConstraint, UniqueConstraint, ForeignKeyConstraint, PrimaryKeyConstraint, text, func
)

from sqlalchemy.dialects.postgresql import *
from sqlalchemy.dialects.postgresql import (
    ARRAY, BIGINT, BIT, BOOLEAN, BYTEA, CHAR, CIDR, DATE,
    DOUBLE_PRECISION, ENUM, FLOAT, HSTORE, INET, INTEGER,
    INTERVAL, JSON, JSONB, MACADDR, NUMERIC, OID, REAL, SMALLINT, TEXT,
    TIME, TIMESTAMP, UUID, VARCHAR, INT4RANGE, INT8RANGE, NUMRANGE,
    DATERANGE, TSRANGE, TSTZRANGE, TSVECTOR, aggregate_order_by )

from flask_appbuilder import Model
from flask_appbuilder.models.mixins import AuditMixin, FileColumn, ImageColumn, UserExtensionMixin
from flask_appbuilder.filemanager import ImageManager, get_file_original_name
from flask_appbuilder.models.decorators import renders

from sqlalchemy_utils import aggregated, force_auto_coercion, observes
from sqlalchemy_utils.types import TSVectorType
from sqlalchemy.ext.associationproxy import association_proxy

from geoalchemy2 import Geometry

# Enums defined in the database



# Miscellaneous Tables
# These tables are used by the application for various purposes

class FlaskSession(Model):
    __tablename__ = 'nx_sessions'

    id = Column(String(256), primary_key=True)
    data = Column(LargeBinary)
    expiry = Column(DateTime, nullable=False)
    created = Column(DateTime, default=func.now())
    modified = Column(DateTime, default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f'<Session {self.id}>'

    @classmethod
    def cleanup_expired(cls, db_session):
        """Remove expired sessions from the database"""
        cls.query.filter(cls.expiry < func.now()).delete()
        db_session.commit()


class Clients(Model):
    __tablename__ = "clients"
    __table_args__ = (
        # Index('clients_email_key', 'email', unique=True),
    )
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    client_name = Column(String(length=255), nullable=False)
    contact_person = Column(String(length=255))
    email = Column(String(length=255), nullable=False, unique=True)
    phone_number = Column(String(length=20))
    business_profile = Column(JSON)
    kyc_status = Column(String(length=20), default=text(''not_verified'::character varying'))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())
    wallets = relationship('Wallets', back_populates='client', foreign_keys='[Wallets.client_id]', lazy='select')

    api_keys = relationship('ApiKeys', back_populates='client', foreign_keys='[ApiKeys.client_id]', lazy='select')


    def __repr__(self):
        return f'<{self.__class__.__name__} {self.email}>'


class Transactions(Model):
    __tablename__ = 'transactions'
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    transaction_id = Column(String(length=50), nullable=False, unique=True)
    client_id = Column(Integer, ForeignKey('clients.id'))
    user_id = Column(Integer, ForeignKey('users.id'))
    amount = Column(Numeric(precision=15, scale=2), nullable=False)
    currency = Column(String(length=10), nullable=False)
    status = Column(String(length=20), default=text(''pending'::character varying'))
    date_time = Column(DateTime, default=func.now())
    transaction_type = Column(String(length=50))
    issuer_card_details = Column(JSON)
    response_code = Column(String(length=10))
    journal_entry = Column(JSON)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())


    dispute = relationship('Disputes', back_populates='transaction', foreign_keys='[Disputes.transaction_id]', lazy='select')

class Users(Model):
    __tablename__ = "users"
    __table_args__ = (
        # Index('users_email_key', 'email', unique=True),
    )
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    email = Column(String(length=255), nullable=False, unique=True)
    password_hash = Column(String(length=255), nullable=False)
    name = Column(String(length=255))
    profile_picture_url = Column(String(length=255))
    role = Column(String(length=50))
    status = Column(String(length=20), default=text(''active'::character varying'))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())
    notifications = relationship('Notifications', back_populates='user', foreign_keys='[Notifications.user_id]', lazy='select')

    logs = relationship('Logs', back_populates='user', foreign_keys='[Logs.user_id]', lazy='select')

    transaction_exports = relationship('TransactionExports', back_populates='user', foreign_keys='[TransactionExports.user_id]', lazy='select')


    def __repr__(self):
        return f'<{self.__class__.__name__}(email={self.email}, name={self.name})>'


class Disputes(Model):
    __tablename__ = "disputes"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    transaction_id = Column(Integer, ForeignKey('transactions.id'))
    status = Column(String(length=20), default=text(''pending'::character varying'))
    reason = Column(Text)
    supporting_document_url = Column(String(length=255))
    tat_expiry = Column(DateTime)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())
    transaction = relationship('Transactions', back_populates='dispute', foreign_keys='[Disputes.transaction_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class Wallets(Model):
    __tablename__ = "wallets"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    client_id = Column(Integer, ForeignKey('clients.id'))
    balance = Column(Numeric(precision=15, scale=2), default=text('0.0'))
    ledger_balance = Column(Numeric(precision=15, scale=2), default=text('0.0'))
    last_updated = Column(DateTime, default=func.now())
    client = relationship('Clients', back_populates='wallets', foreign_keys='[Wallets.client_id]', lazy='select')
    wallet_transactions = relationship('WalletTransactions', back_populates='wallet', foreign_keys='[WalletTransactions.wallet_id]', lazy='select')


    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class WalletTransactions(Model):
    __tablename__ = "wallet_transactions"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    wallet_id = Column(Integer, ForeignKey('wallets.id'))
    transaction_type = Column(String(length=50), nullable=False)
    amount = Column(Numeric(precision=15, scale=2), nullable=False)
    status = Column(String(length=20), default=text(''successful'::character varying'))
    timestamp = Column(DateTime, default=func.now())
    reference = Column(String(length=50))
    wallet = relationship('Wallets', back_populates='wallet_transactions', foreign_keys='[WalletTransactions.wallet_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class Notifications(Model):
    __tablename__ = "notifications"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'))
    email_notifications = Column(Boolean, default=True)
    sms_notifications = Column(Boolean, default=True)
    preferences = Column(JSON)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())
    user = relationship('Users', back_populates='notifications', foreign_keys='[Notifications.user_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class ApiKeys(Model):
    __tablename__ = "api_keys"
    __table_args__ = (
        # Index('api_keys_api_key_key', 'api_key', unique=True),
    )
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    client_id = Column(Integer, ForeignKey('clients.id'))
    api_key = Column(String(length=255), nullable=False, unique=True)
    status = Column(String(length=20), default=text(''active'::character varying'))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())
    client = relationship('Clients', back_populates='api_keys', foreign_keys='[ApiKeys.client_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class Teams(Model):
    __tablename__ = 'teams'
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    client_id = Column(Integer, ForeignKey('clients.id'))
    team_member_id = Column(Integer, ForeignKey('users.id'))
    role = Column(String(length=50))
    status = Column(String(length=20), default=text(''active'::character varying'))
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())


class Logs(Model):
    __tablename__ = "logs"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'))
    action = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=func.now())
    ip_address = Column(String(length=50))
    metadata = Column(JSON)
    user = relationship('Users', back_populates='logs', foreign_keys='[Logs.user_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class Filters(Model):
    __tablename__ = "filters"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    filter_name = Column(String(length=255), nullable=False)
    filter_type = Column(String(length=50), nullable=False)
    filter_value = Column(Text)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now())

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class TransactionExports(Model):
    __tablename__ = "transaction_exports"
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'))
    format = Column(String(length=10), nullable=False)
    status = Column(String(length=20), default=text(''generated'::character varying'))
    file_url = Column(String(length=255))
    created_at = Column(DateTime, default=func.now())
    user = relationship('Users', back_populates='transaction_exports', foreign_keys='[TransactionExports.user_id]', lazy='select')

    def __repr__(self):
        return f'<{self.__class__.__name__} {self.id}>'


class SettlementDetails(Model):
    __tablename__ = 'settlement_details'
    id = Column(Integer, autoincrement=True, primary_key=True, nullable=False)
    transaction_id = Column(Integer, ForeignKey('transactions.id'))
    client_id = Column(Integer, ForeignKey('clients.id'))
    settlement_status = Column(String(length=20), default=text(''pending'::character varying'))
    settlement_date = Column(Date)
    amount = Column(Numeric(precision=15, scale=2))
    created_at = Column(DateTime, default=func.now())

